[project]
name = "zerolanliverobot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.0",
    "jwt>=1.4.0",
    "pycryptodome>=3.23.0",
    "pycryptodomex>=3.23.0",
    "qrcode-terminal>=0.8",
]
